trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    filePath: 'scripts/cibuild'
  displayName: 'Run cibuild script (build and test)'
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Pay-As-You-Go(d53d960e-ac9c-49ae-a41d-d6aea81418ed)'
    azureContainerRegistry: '{"loginServer":"sgcomponentstest.azurecr.io", "id" : "/subscriptions/d53d960e-ac9c-49ae-a41d-d6aea81418ed/resourceGroups/pc-test-manual-resources/providers/Microsoft.ContainerRegistry/registries/sgcomponentstest"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Build services'
  displayName: 'Build oaff container image'
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Pay-As-You-Go(d53d960e-ac9c-49ae-a41d-d6aea81418ed)'
    azureContainerRegistry: '{"loginServer":"sgcomponentstest.azurecr.io", "id" : "/subscriptions/d53d960e-ac9c-49ae-a41d-d6aea81418ed/resourceGroups/pc-test-manual-resources/providers/Microsoft.ContainerRegistry/registries/sgcomponentstest"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Push services'